export enum BandeiraCartao {
   VISA = "VISA",
   MASTERCARD = "MASTERCARD",
   AMERICAN_EXPRESS = "AMERICAN_EXPRESS",
   DISCOVER = "DISCOVER",
   DINERS_CLUB = "DINERS_CLUB",
   JCB = "JCB",
   OUTRAS = "OUTRAS",
   NAO_DEFINIDO = "NAO_DEFINIDO",
}
