enum CardBrand {
   VISA = "VISA",
   MASTERCARD = "MASTERCARD",
   AMERICAN_EXPRESS = "AMERICAN_EXPRESS",
   DISCOVER = "DISCOVER",
   DINERS_CLUB = "DINERS_CLUB",
   JCB = "JCB",
   OUTRAS = "OUTRAS",
   UNDEFINED = "UNDEFINED",
}

export default CardBrand;
