enum CardBrand {
   VISA = "VISA",
   MASTERCARD = "MASTERCARD",
   AMERICAN_EXPRESS = "AMERICAN_EXPRESS",
   DISCOVER = "DISCOVER",
   DINERS_CLUB = "DINERS_CLUB",
   JCB = "JCB",
   OUTRA = "OUTRA",
   UNDEFINED = "UNDEFINED",
}

export default CardBrand;
